### ISSUE TITLE
Pop-up view 

### ISSUE THREAD

**Issue by BaptisteLalanne** [BaptisteLalanne/Privacy-Keeper#1]
https://www.figma.com/file/XIcr9v30znEOtJzZ2LWDnx/Cookie-extension?node-id=0%3A1

Finish the pop-up view on Figma in order to start the development 
- Describe all possibilities of click
- Create as many components as click possibilities for the pop-up view only

**Comment by dt-mark** [comment]
There are still the detailed views left to do, but that'll come once we have more concrete measures and evaluations to display
