### ISSUE TITLE
Update the README and add LICENSE

### ISSUE THREAD

**Issue by BaptisteLalanne** [BaptisteLalanne/Privacy-Keeper#15]
We need to describe who is working on the project, the goal of our extension...

Don't forget to credit the theses used and the GitHub pages from which you take some code

About the license, add the license to the repo and don't forget to fill it well ! :)

**Comment by tomperr** [comment]
I worked on it in `docs/update-readme` branch, but the "Trackers" section is empty for the moment.
Can someone of the "tracker team" do it?
@AmL-Dev @BaptisteLalanne @dt-mark @Loannl4 

Related commits: 003f0324bd434696bc864c376dd874a397b1d157, 25a4621179aa8ae48c8ac5da2f4d93f0a9e2100e
