### ISSUE TITLE
Cookies : delete unused cookies

### ISSUE THREAD

**Issue by ArthurDurand** [BaptisteLalanne/Privacy-Keeper#19]
Title

**Comment by GrannySmith21** [comment]
chargement d'une page :
    -> document.cookie = liste des cookies de la page
    -> mise à jour des cookies : fichier json sauvegardé en local

démarrage du navigateur :
    -> check des cookies n'ayant pas été modifié dans la durée établie par l'utilisateur
    -> suppresion de ces cookies

**Comment by ArthurDurand** [comment]
Done
