### ISSUE TITLE
Set up the extension development framework / architecture

### ISSUE THREAD

**Issue by dt-mark** [BaptisteLalanne/Privacy-Keeper#24]
Familiarize ourselves with extension development (see Arthur's document on Teams https://insalyonfrance.sharepoint.com/:w:/s/H4211/EeBiVP_tuxVIk-LA3QO5Jy4BzHLU9MWL_4Lsd-J3RuOGGQ?e=NLcyKD)

**Comment by BaptisteLalanne** [comment]
Well done by @tomperr
