### ISSUE TITLE
Cookies : Whitelist website to not delete cookies

### ISSUE THREAD

**Issue by ArthurDurand** [BaptisteLalanne/Privacy-Keeper#26]
Choose which website you want to keep its cookies when closing its tab
Settings

**Comment by tomperr** [comment]
Doesn't it make more sense to use a blacklist instead of a whitelist?

**Comment by ArthurDurand** [comment]
Nope. On delete les cookies des sites sur lesquels on ne va pas pendant longtemps. Donc on whitelist des sites pour dire qu'on garde leurs cookies.
On peut aussi bl des sites pour delete les cookies instantannéments

**Comment by ArthurDurand** [comment]
done - waiting for pull request

**Comment by GrannySmith21** [comment]
/
